config/routes.rb
TaggingExample::Application.routes.draw do
  resources :articles
  root "articles#index"
  get "/", to: "article#index", as: :tag
end

app/models/article.rb
class Article < ActiveRecord::Base
	acts_as_ordered_taggable
	validates :title, :content, :tag_list, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		if params[:tag]
			@articles = Article.tagged_with(params[:tag])
		else
			@articles = Article.all
		end
	end

	def show
		@article = Article.find(params[:id])
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		if @article.save
			flash[:success] = "Success post your article"
			redirect_to root_url
		else
			render :new
		end
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		if @article.update(article_params)
			flash[:success] = "Success update your article"
			redirect_to article_url(@article)
		else
			render :edit
		end
	end

	def destroy
		article = Article.find(params[:id])
		title = article.title
		article.delete
		flash[:success] = "Success delete your article #{title}"
		redirect_to root_url
	end

	private

	def article_params
		params.require(:article).permit(:title, :content, :tag_list)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def alert_struct(type, key=nil, message)
		content_tag :div, class: "alert alert-#{type} alert-dismissible" do 
			concat content_tag(:button, 'x', class: "close", data: {dismiss: "alert"})
			concat key ? "#{key}: #{message}" : "#{message}"
		end
	end

	def show_errors(type, error_messages)
		error_messages.each do |field_type, message|
			concat alert_struct(type, field_type, message.shift)
		end
		nil
	end

	def list_tag(instance) 
		instance.tag_list.map do |tag|
			link_to "#{tag}", tag_path(tag: tag)
		end.join(',').html_safe
	end

	def edit_tag(instance)
		instance.tag_list.each do |tag|
			concat content_tag(:li, tag)
		end
		nil
	end

	def have_a_tag?
		!params[:tag].nil?
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<div class="row">
	<%= show_errors("danger", @article.errors.messages) unless @article.errors.nil? %>
	<div class="col-xs-6 col-xs-offset-3">
		<h1>Edit Article</h1>
		<%= form_for @article, url: article_path(@article) do |f|%>
			<div class="form-group">
				<%= f.label :title %>
				<%= f.text_field :title, class: "form-control", placeholder: "Enter your title" %>
			</div>
			<div class="form-group">
				<%= f.label :tag_list, "tag" %>
				<ul class="article-tags">
					<%= edit_tag(@article) %>
				</ul>
			</div>
			<div class="form-group">
				<%= f.label :content %>
				<%= f.text_area :content, class: "form-control", rows: "15", placeholder: "Enter your content"  %>
			</div>
			<%= f.button "Update Article", class: "btn btn-success" %>
		<% end %>
	</div>
</div>

app/views/articles/index.html.erb
<div class="row">
	<%= alert_struct("success", flash[:success]) unless flash.empty? %>
	<div class="col-xs-6">
		<h1>Articles</h1>
		<%= have_a_tag? ? link_to("all articles", root_path) : link_to("Create new article", new_article_path) %>
		<% @articles.each do |article| %>
			<div class="article">
				<h3><%= article.title %></h3>
				<p><%= article.content %></p>
				<p>tag: <%= list_tag(article) %></p>
				<%= link_to "show", article_path(article) %> |
				<%= link_to "edit", edit_article_path(article) %> |
				<%= link_to "destroy", article_path(article), method: :delete %>
			</div>
		<% end %>
	</div>
</div>

app/views/articles/new.html.erb
<div class="row">
	<%= show_errors("danger", @article.errors.messages) unless @article.errors.nil? %>
	<div class="col-xs-6 col-xs-offset-3">
		<h1>New Article</h1>
		<%= form_for @article do |f| %>
			<div class="form-group">
				<%= f.label :title %>
				<%= f.text_field :title, class: "form-control", placeholder: "Enter your title" %>
			</div>
			<div class="form-group">
				<%= f.label :tag_list, "tag" %>
				<ul class="article-tags"></ul>
			</div>
			<div class="form-group">
				<%= f.label :content %>
				<%= f.text_area :content, class: "form-control", rows: "15", placeholder: "Enter your content"  %>
			</div>
			<%= f.button "Create Article", class: "btn btn-success" %>
		<% end %>
	</div>
</div>

app/views/articles/show.html.erb
<div class="row">
	<%= alert_struct("success", flash[:success]) unless flash.empty? %>
	<div class="col-xs-6 col-xs-offset-3">
		<div class="show-article">
				<h3><%= @article.title %></h3>
				<p><%= @article.content %></p>
				<p>tag: <%= list_tag(@article) %></p>
				<div class="center">
					<%= link_to "articles", articles_path %> | 
					<%= link_to "edit", edit_article_path(@article) %> |
					<%= link_to "destroy", article_path(@article), method: :delete %>
				</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaggingExample</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% unless @article.errors.nil? %>
	<%= show_errors("danger", @article.errors.messages) %>
<% end %>